### PR TITLE
Fix for #22

### PR DESCRIPTION
**Pull request by chris-steele**
Maybe naive, but tested working. Would appreciate your thoughts @oliverfoster as ever.
#22

### CODE REVIEW

**Comment by oliverfoster** [comment]
did you have an example schema in mind?

**Comment by oliverfoster** [comment]
It appears to me that @moloko wanted the defaults from https://github.com/adaptlearning/adapt-contrib-bookmarking/blob/master/properties.schema#L14 to go into the course.json, config.json etc.

I can't see any modifications to the course / config.json?

**Comment by chris-steele** [comment]
Yeah this fix is just for what rub-cli does with globals. I haven't done anything for https://github.com/adaptlearning/adapt-cli/issues/94 yet (this will be something I do in adapt-cli)

**Comment by oliverfoster** [comment]
Do you have an example of a nested globals property? I'm struggling to find one.

**Comment by chris-steele** [comment]
Sure. Got an example from a bespoke version of spoor here: https://dev.kineo.com/svn/us-lcel-17186/trunk/dev/src/extensions/adapt-contrib-spoor/properties.schema - the `_buttons` property would be omitted without this change.

**Review by oliverfoster — APPROVED** [review]

**Pull request merged**
